/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loumeng_jnisimple_JNIsimple */

#ifndef _Included_com_loumeng_jnisimple_JNIsimple
#define _Included_com_loumeng_jnisimple_JNIsimple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loumeng_jnisimple_JNIsimple
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loumeng_jnisimple_JNIsimple_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
